# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GroceryApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GroceryApp
  pod 'Firebase/Core'

  pod 'Firebase/Database'

  target 'GroceryAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GroceryAppUITests' do
    # Pods for testing
  end

end
