# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '1-HelloRxSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 1-HelloRxSwift
  pod 'RxSwift'
  pod 'RxCocoa'

  target '1-HelloRxSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '1-HelloRxSwiftUITests' do
    # Pods for testing
  end

end
